# Generated by Django 5.0.3 on 2024-04-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='round1match1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M1', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M2', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M3', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M4', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M5', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M6', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M7', to='MainPage.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round1match8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R1M8', to='MainPage.match'),
        ),
    ]
