# Generated by Django 5.0.3 on 2024-04-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_alter_tournament_round1match1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round2match1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R2M1', to='MainPage.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round2match2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R2M2', to='MainPage.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round2match3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R2M3', to='MainPage.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='round2match4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='R2M4', to='MainPage.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_round_matches_created',
            field=models.BooleanField(default=False),
        ),
    ]
